### ISSUE TITLE
Not possible to use generic client with AboutServiceAPI 

### ISSUE THREAD

**Issue by piyushgupta243** [Informatiqal/qlik-rest-api#225]
First of all, thank you for your work. Its really a nice library to interact with Qlik.

I am trying to use the Generic client to access Qlik Product info using https://help.qlik.com/en-US/sense-developer/November2022/Subsystems/AboutServiceAPI/Content/Sense_AboutServiceAPI/AboutServiceAPI-Introduction.htm
But it does not work.
I am authenticating using the certificates. This works for QRS api but not for about service api.
Can you share any insight?

**Comment by countnazgul** [comment]
Unfortunatelly certificates authentication dont make sense in the case of the `About` service. 

Certificates are to be used when connecting to the backend services (QRS, Proxy etc). `About` service is a "frontend" service and the autnetication methods there should be - JWT, session, ticket or header.

That being said ...

The certificates workaround will be first to connect to the `Proxy` service and generate a `ticket` for the user and then pass the `ticket` to the `Generic` client config and call the `About` service endpoint:

```js
    // create https agent with the certificates
    const httpsAgent = new https.Agent({
      rejectUnauthorized: false,
      cert: fs.readFileSync(`${process.env.TEST_CERT}/client.pem`),
      key: fs.readFileSync(`${process.env.TEST_CERT}/client_key.pem`),
    });

    // create new Proxy client
    const proxyClient = new QlikProxyClient({
      host: `${process.env.TEST_HOST}`,
      port: 4243,
      httpsAgent: httpsAgent,
      authentication: {
        user_dir: `${process.env.SENSE_USER_DIRECTORY}`,
        user_name: `${process.env.SENSE_USER_NAME}`,
      },
    });

    // call Proxy "ticket" endpoint to generate new ticket
    // for the provided user
    const ticket = await proxyClient
      .Post("ticket", {
        UserDirectory: `${process.env.SENSE_USER_DIRECTORY}`,
        UserId: `${process.env.SENSE_USER_NAME}`,
        Attributes: [],
      })
      .then((res) => res.data.Ticket);

    // create new generic client by providing the ticket
    // generated from the Proxy API call
    const genericClient = new QlikGenericRestClient({
      host: `${process.env.TEST_HOST}`,
      port: 443,
      httpsAgent: httpsAgent,
      authentication: {
        ticket,
      },
    });

    // call About service endpoint
    const aboutResponse = await genericClient.Get("api/about/v1/SystemInfo");
```

The above code will return:
![image](https://github.com/Informatiqal/qlik-rest-api/assets/22850/4200d386-41b2-460f-8172-69b78b74a92e)

P.S. Once the ticket is consumed then it can't be used anymore. If you need to make multiple calls to the `About` service then you can use the Proxy client to generate session and pass the resulted `sessionId` to the `Generic` client authentication property. Let me know if you need some sample code for this case

**Comment by piyushgupta243** [comment]
Thanks for the great example. This is something what i was looking for and tested it on my side as well and it works as expected.
I agree its a front-end service and should be authenticated with the methods you mentioned. For my use-case, i dont have access to the password of the user and since i dont manage the qlik instance so, have limited access to what i can do.
i saw the ticket end-point and was trying to use the same, what i was missing was:
```
    authentication: {
      ticket
    }
```
in the client config of generic rest client (P.S I am very new to ts and js :) ).
So, you can close this issue

Also, I saw in your documentation that there will be a separate repo for qlik-engine-api. Are you planning to release it soon?

**Comment by countnazgul** [comment]
There are 2 Engine API - REST and JSON-RPC

- REST API - small set of endpoints mostly used for healthcheck purposes. This should be covered by the [current package](https://github.com/Informatiqal/qlik-rest-api#engine-api-healthcheck-of-single-engine)
- [JSON-RPC](https://help.qlik.com/en-US/sense-developer/August2023/Subsystems/EngineAPI/Content/Sense_EngineAPI/GettingStarted/connecting-to-engine-api.htm) - this is the "main" engine api that is used to interact with the apps - get charts data, create new objects in a app, make selections, export data etc. This API is `web socket` based and Qlik released their own JS package to handle the communication - [Enigma.js](https://github.com/qlik-oss/enigma.js/). Have a look at this [example](https://github.com/qlik-oss/enigma.js/blob/master/examples/authentication/sense-using-certificates/certificates.js) on how to connect to an engine/app with certificates
