### ISSUE TITLE
Cannot pass filters or order by statements

### ISSUE THREAD

**Issue by aburnsy** [Informatiqal/qlik-rest-api#3]
I think the XrfKey should come between the request and the  filter. There doesn't seem to be a way to pass that to the Get method and have a valid output
If I pass 
/qrs/app/hublist?filter=Name%20eq%20%27MyappName%27
The xrf is appended, but Qlik seems to fail to recognise the filter.

**Comment by countnazgul** [comment]
Whats the url that you are passing into the `Get` method? `/qrs/app/hublist?filter=Name%20eq%20%27MyappName%27`?

If this is the case then the url will be wrong and the result will be an error. No need to pass `/qrs` to the url and no need to url encode the parameters as well. 

If you just pass `app/hublist?filter=Name eq 'MyappName'`?

This works for me:
![image](https://user-images.githubusercontent.com/22850/132708250-2f1a4633-fc4c-438b-8bd1-e0b9dc41f7f3.png)

Thanks for the issue btw :)

**Comment by aburnsy** [comment]
I'm really sorry, I can see now what I was doing. 
I messed up my express router settings, so it was stripping out the query part of the request in the req.params.request. 
Thanks so much for responding! Really enjoying the library - its a huge help!

**Comment by countnazgul** [comment]
Not a pbolem at all!
Any issues please let me know
