### ISSUE TITLE
Documentation Request - Passing Additional Auth Attributes

### ISSUE THREAD

**Issue by aburnsy** [Informatiqal/qlik-rest-api#5]
Hi Stefan,

I'm unsure if this is an issue itself or its just a matter of documentation. When authenticating I need to pass over additional attributes that will be used in Security Rules + Section Access. 

Using enigma I think you pass something like this:
Attributes: [{ Group: '1234' }, { Group: '5678' }, { CLIENT: 'COCA COLA' }]

Is this available today? I've tried a few different variations and can't seem to get it to work. It might just be how I am doing it though.

Thanks again,
Andy

**Comment by countnazgul** [comment]
Hmmm not sure i can find anything in Qlik's documentation about it. Any chance these attributes are to be used with JWT authentication?

**Comment by aburnsy** [comment]
Not necessarily. One example below:

https://help.qlik.com/en-US/sense-developer/April2020/Subsystems/ProxyServiceAPI/Content/Sense_ProxyServiceAPI/ProxyServiceAPI-ProxyServiceAPI-Authentication-Ticket-Add.htm
